#include<bits/stdc++.h>
using namespace std;
#define ll long long

/* [💭] [💡] [🎈] */

void ans() {
   int n , m;
   cin >> n >> m;
   if(n > m) {
      swap(n , m);
   }
   if(n + 3 > m) {
     cout <<"Yes\n";
   }
   else {
     cout <<"No\n";
   }
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    ans();
    return 0;
}

#include<bits/stdc++.h>
using namespace std;
#define ll long long

/* [💭] [💡] [🎈] */

void ans() {
   int n , m;
   cin >> n >> m;
   if(n > m) {
      swap(n , m);
   }
   if(n + 3 > m) {
     cout <<"Yes\n";
   }
   else {
     cout <<"No\n";
   }
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    ans();
    return 0;
}

Submission Info
